# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e86524e02996fe25d22785953f1496c90d0f55f12faa2e5bfb0c1a3942beda2b63925e68fb1336a38f175d3e0b0bd7a24c7c66f0317e8d6c623d5e95ea5e8e01

test:
  secret_key_base: 2147713e6384aed9b69c55eb67cc15fe21bf4528b5dcb200b4dba449740669bf2560d2bb537aa63f0eb1487316b999e4640fba09bfd3fd0d6ce666045cbba96a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
