toolbar:
  - undo redo | styleselect | bold italic underline | bullist numlist outdent indent | link image table
plugins:
  - image
  - link
  - table
menubar: false
statusbar: false
setup :
  function(ed) {
    ed.on('init', function() {
      this.getDoc().body.style.fontSize = '14px';
    });
  }
